### ISSUE TITLE
Image fields Alt attribute

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/acf-yoast-seo-validation#3]
Image fields are supported by fetching the thumbnail HTML. However, the image alt attribute is not provided in the thumbnail, so Yoast keeps complaining about missing alt tags.

**Comment by TimVevida** [comment]
This issue is resolved by updating ACF PRO to version 5.3.4.

**Comment by mjot** [comment]
Same Problem with the latest versions:
Wordpress 4.3.5
ACF Pro: 5.3.9.2
Yoast: 3.3.2

**Comment by solverat** [comment]
he @mjot, like TimVevida said this issue is resolved when updating ACF Pro to 5.3.4.

**Comment by mjot** [comment]
html,body{font-size:12px;background-color:#fff;color:#333;font-family:sans-serif,Arial,Verdana,Trebuchet MS;line-height:1.4;}Hi Tim,

I've seen his message, so the solution is, that I should downgrade from ACF Pro: 5.3.9.2 to 5.3.4??

I've the latest version from ACF Pro.

Thanks,

Martin



Stefan Hagspiel schrieb am 28.06.2016 09:08:


he @mjot, like TimVevida said this issue is resolved when updating ACF Pro to 5.3.4.

**Comment by solverat** [comment]
sorry, my mistake. downgrading isn't a good option though. :) so we should take a close look.
